/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BannerRouteImport } from './routes/banner'
import { Route as GoRouteImport } from './routes/go'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BannerRoute = BannerRouteImport.update({
  id: '/banner',
  path: '/banner',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banner': typeof BannerRoute
  '/go': typeof GoRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/partner': typeof PartnerRoute
  '/watch': typeof WatchRoute
  '/api/rtc': typeof ApiRtcRoute
  '/join/$code': typeof JoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banner': typeof BannerRoute
  '/go': typeof GoRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/partner': typeof PartnerRoute
  '/watch': typeof WatchRoute
  '/api/rtc': typeof ApiRtcRoute
  '/join/$code': typeof JoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banner': typeof BannerRoute
  '/go': typeof GoRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/partner': typeof PartnerRoute
  '/watch': typeof WatchRoute
  '/api/rtc': typeof ApiRtcRoute
  '/join/$code': typeof JoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banner'
    | '/go'
    | '/library'
    | '/login'
    | '/ops'
    | '/partner'
    | '/watch'
    | '/api/rtc'
    | '/join/$code'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banner'
    | '/go'
    | '/library'
    | '/login'
    | '/ops'
    | '/partner'
    | '/watch'
    | '/api/rtc'
    | '/join/$code'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/banner'
    | '/go'
    | '/library'
    | '/login'
    | '/ops'
    | '/partner'
    | '/watch'
    | '/api/rtc'
    | '/join/$code'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BannerRoute: typeof BannerRoute
  GoRoute: typeof GoRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  PartnerRoute: typeof PartnerRoute
  WatchRoute: typeof WatchRoute
  ApiRtcRoute: typeof ApiRtcRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banner': {
      id: '/banner'
      path: '/banner'
      fullPath: '/banner'
      preLoaderRoute: typeof BannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BannerRoute: BannerRoute,
  GoRoute: GoRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  PartnerRoute: PartnerRoute,
  WatchRoute: WatchRoute,
  ApiRtcRoute: ApiRtcRoute,
  JoinCodeRoute: JoinCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
